# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_processing_system7_0_0 || ORIG_REF_NAME==top_processing_system7_0_0} -quiet] -quiet

# IP: bd/top/ip/top_Wordle_Matcher_HDL_0_4/top_Wordle_Matcher_HDL_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_Wordle_Matcher_HDL_0_4 || ORIG_REF_NAME==top_Wordle_Matcher_HDL_0_4} -quiet] -quiet

# IP: bd/top/ip/top_axi_smc_3/top_axi_smc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_smc_3 || ORIG_REF_NAME==top_axi_smc_3} -quiet] -quiet

# IP: bd/top/ip/top_rst_ps7_0_100M_3/top_rst_ps7_0_100M_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_ps7_0_100M_3 || ORIG_REF_NAME==top_rst_ps7_0_100M_3} -quiet] -quiet

# XDC: d:/Xilinx/reconfig/wordle_fsm_platform/wordle_fsm_platform.gen/sources_1/bd/top/top_ooc.xdc
