# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx/reconfig/wordle_fsm_platform/wordle_fsm_platform.srcs/sources_1/bd/top/ip/top_rst_ps7_0_100M_3/top_rst_ps7_0_100M_3.xci
# IP: The module: 'top_rst_ps7_0_100M_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/reconfig/wordle_fsm_platform/wordle_fsm_platform.gen/sources_1/bd/top/ip/top_rst_ps7_0_100M_3/top_rst_ps7_0_100M_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_ps7_0_100M_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Xilinx/reconfig/wordle_fsm_platform/wordle_fsm_platform.gen/sources_1/bd/top/ip/top_rst_ps7_0_100M_3/top_rst_ps7_0_100M_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_ps7_0_100M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Xilinx/reconfig/wordle_fsm_platform/wordle_fsm_platform.gen/sources_1/bd/top/ip/top_rst_ps7_0_100M_3/top_rst_ps7_0_100M_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_ps7_0_100M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Xilinx/reconfig/wordle_fsm_platform/wordle_fsm_platform.srcs/sources_1/bd/top/ip/top_rst_ps7_0_100M_3/top_rst_ps7_0_100M_3.xci
# IP: The module: 'top_rst_ps7_0_100M_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/reconfig/wordle_fsm_platform/wordle_fsm_platform.gen/sources_1/bd/top/ip/top_rst_ps7_0_100M_3/top_rst_ps7_0_100M_3_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_ps7_0_100M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Xilinx/reconfig/wordle_fsm_platform/wordle_fsm_platform.gen/sources_1/bd/top/ip/top_rst_ps7_0_100M_3/top_rst_ps7_0_100M_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_ps7_0_100M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Xilinx/reconfig/wordle_fsm_platform/wordle_fsm_platform.gen/sources_1/bd/top/ip/top_rst_ps7_0_100M_3/top_rst_ps7_0_100M_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_rst_ps7_0_100M_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
