domain_path: D:\Xilinx\reconfig\wordle_fsm_platform\wordle_fsm_platform.vitis\platform\export\platform\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
