domain_path: D:\Xilinx\reconfig\wordle_fsm_platform\wordle_fsm_platform.vitis\platform\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: D:\Xilinx\Vitis\2024.2\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
lang: c
